### ISSUE TITLE
Make the mode compatible with KaSim 4

### ISSUE THREAD

**Issue by jkrivine** [sstucki/kappa-emacs#8]
It would be great if the kappa mode was made compatible with the new command line.
The most important feature is the C/c C/r command that should launch:
KaSim -i input.ka -u event -l 10000 -p 10 -o data.csv

**Comment by sstucki** [comment]
Thanks for reporting this issue @jkrivine.

As far as I can see the difference between the old and new command lines is
 - `-t <time>` changed to `-u time -l <time>`
 - `-e <events>` changed to `-u event -l <events>`

Is that correct?
Also, currently the default output file name is `data.out`, do you want me to change that to `data.csv`?

Do you think it would make sense to keep a branch `KaSim3-compat` of the Emacs mode for backwards compatibility with KaSim 3 and earlier?

**Comment by sstucki** [comment]
More questions:
 - it seems the command line option `--emacs-mode` does no longer exist. I guess it is no longer necessary?
 - there are some warnings when I run `abc.ka`
   ```
   File "/home/sast/projects/kappa/KaSim/models/abc.ka", line 21, characters 6-19:
   Warning: Deprecated variable syntax: use |kappa instance| instead.
   ```
   but I guess these are to do with the model, not my handling of the command line, correct?

**Comment by jkrivine** [comment]
Yes it's the commands you quote. Making a branch for Kasim 3 might be a good idea. Ultimately a syntax highlight for the new notation for rules A (x![1>2]) would be awesome. 

Le 30 juin 2017 07:59:15 GMT+02:00, Sandro Stucki <notifications@github.com> a écrit :
>Thanks for reporting this issue @jkrivine.
>
>As far as I can see the difference between the old and new command
>lines is
> - `-t <time>` changed to `-u time -l <time>`
> - `-e <events>` changed to `-u event -l <events>`
>
>Is that correct?
>Also, currently the default output file name is `data.out`, do you want
>me to change that to `data.csv`?
>
>Do you think it would make sense to keep a branch `KaSim3-compat` of
>the Emacs mode for backwards compatibility with KaSim 3 and earlier? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sstucki/kappa-emacs/issues/8#issuecomment-312182528

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by jkrivine** [comment]
Yes now Kappa is typed! So |.| cast a kappa expression to an integer (the number of matches of the expression) !

Le 30 juin 2017 08:29:33 GMT+02:00, Sandro Stucki <notifications@github.com> a écrit :
>More questions:
>- it seems the command line option `--emacs-mode` does no longer exist.
>I guess it is no longer necessary?
> - there are some warnings when I run `abc.ka`
>   ```
>File "/home/sast/projects/kappa/KaSim/models/abc.ka", line 21,
>characters 6-19:
>   Warning: Deprecated variable syntax: use |kappa instance| instead.
>   ```
>but I guess these are to do with the model, not my handling of the
>command line, correct?
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sstucki/kappa-emacs/issues/8#issuecomment-312186644

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by sstucki** [comment]
> Yes it's the commands you quote. Making a branch for Kasim 3 might be a good idea.

Done.

> Ultimately a syntax highlight for the new notation for rules A (x![1>2]) would be awesome.

Yes, but I guess that will have to wait until later this year, too busy right now, sorry.

> Yes now Kappa is typed! So |.| cast a kappa expression to an integer (the number of matches of the expression) !

Cool! I'll have to catch up with all the new features you guys have been implementing soon too.
